[project]
name = "beanie-crudrouter"
version = "0.1.0"
description = "CrudRouter for beanie odm based on fastapi_crudrouter"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beanie>=1.27.0",
    "fastapi-crudrouter>=0.8.6",
]
